fix typo and add git remote -v

diff --git a/.github/workflows/generate_reaper_plugin_functions.yml b/.github/workflows/generate_reaper_plugin_functions.yml
--- a/.github/workflows/generate_reaper_plugin_functions.yml
+++ b/.github/workflows/generate_reaper_plugin_functions.yml
@@ -86,7 +86,7 @@ jobs:
           latest_version=${{ needs.check-reaper-version.outputs.latest_version }}
           nix build .#reaper-plugin-functions
           cp result/include/reaper_plugin_functions.h temp/reaper-sdk/sdk/reaper_plugin_functions.h
-          generated_version=$(cat temp/reaper-sdk/sdk/reaper_plugin_function.h | grep -oP '// Generated by REAPER v\K[0-9]+(\.[0-9]+)+' || echo "Current Version Not Found")
+          generated_version=$(cat temp/reaper-sdk/sdk/reaper_plugin_functions.h | grep -oP '// Generated by REAPER v\K[0-9]+(\.[0-9]+)+' || echo "Current Version Not Found")
           if [[ "$generated_version" -ne "$latest_version" ]]; then
               echo "Expected version '$latest_version' but the generated version is '$generated_version'"
               exit 1
@@ -98,6 +98,7 @@ jobs:
           git config --global user.email "cloudscythelabs@gmail.com"
           git config --global user.name "Cloud Scythe Labs"
           cd temp/reaper-sdk/sdk
+          git remote -v
           git status
           git checkout -b update-header-${latest_version}
           git add reaper_plugin_functions.h
