rm exit 1

diff --git a/.github/workflows/generate_reaper_plugin_functions.yml b/.github/workflows/generate_reaper_plugin_functions.yml
--- a/.github/workflows/generate_reaper_plugin_functions.yml
+++ b/.github/workflows/generate_reaper_plugin_functions.yml
@@ -37,7 +37,7 @@ jobs:
         run: |
           # Extract the full version number from the generated header file
           # and compare it to the latest version on reaper.fm download page.
-          current_version=$(curl -s https://raw.githubusercontent.com/justinfrankel/reaper-sdk/main/sdk/reaper_plugin_functions.h | grep -oP '// Generated by REAPER v\K[0-9]+(\.[0-9]+)+' || echo "Current Version Not Found" & exit 1)
+          current_version=$(curl -s https://raw.githubusercontent.com/justinfrankel/reaper-sdk/main/sdk/reaper_plugin_functions.h | grep -oP '// Generated by REAPER v\K[0-9]+(\.[0-9]+)+' || echo "Current Version Not Found")
           echo "Current version: $current_version"
           latest_version=${{ steps.get_version.outputs.latest_version }}
           if [[ "$(printf '%s\n' "$current_version" "$latest_version" | sort -V | head -n 1)" != "$latest_version" ]]; then
@@ -86,7 +86,7 @@ jobs:
           latest_version=${{ needs.check-reaper-version.outputs.latest_version }}
           nix build .#reaper-plugin-functions
           cp result/include/reaper_plugin_functions.h temp/reaper-sdk/sdk/reaper_plugin_functions.h
-          generated_version=$(cat temp/reaper-sdk/sdk/reaper_plugin_function.h | grep -oP '// Generated by REAPER v\K[0-9]+(\.[0-9]+)+' || echo "Current Version Not Found" & exit 1)
+          generated_version=$(cat temp/reaper-sdk/sdk/reaper_plugin_function.h | grep -oP '// Generated by REAPER v\K[0-9]+(\.[0-9]+)+' || echo "Current Version Not Found")
           if [[ "$generated_version" -ne "$latest_version" ]]; then
               echo "Expected version '$latest_version' but the generated version is '$generated_version'"
               exit 1
