use nix generated header file

diff --git a/.github/workflows/generate_reaper_plugin_functions.yml b/.github/workflows/generate_reaper_plugin_functions.yml
--- a/.github/workflows/generate_reaper_plugin_functions.yml
+++ b/.github/workflows/generate_reaper_plugin_functions.yml
@@ -37,7 +37,8 @@ jobs:
         run: |
           # Extract the full version number from the generated header file
           # and compare it to the latest version on reaper.fm download page.
-          current_version=$(curl -s https://raw.githubusercontent.com/justinfrankel/reaper-sdk/main/sdk/reaper_plugin_functions.h | grep -oP '// Generated by REAPER v\K[0-9]+(\.[0-9]+)+' || echo "Current Version Not Found")
+          current_version=$(curl -s https://raw.githubusercontent.com/justinfrankel/reaper-sdk/main/sdk/reaper_plugin_functions.h | grep -oP '// Generated by REAPER v\K[0-9]+(\.[0-9]+)+' || echo "Current Version Not Found" & exit 1)
+          echo "Current version: $current_version"
           latest_version=${{ steps.get_version.outputs.latest_version }}
           if [[ "$(printf '%s\n' "$current_version" "$latest_version" | sort -V | head -n 1)" != "$latest_version" ]]; then
             echo "Update needed"
@@ -71,31 +72,10 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      # - name: Set up Nix
-      #   uses: cachix/install-nix-action@v17
+      - name: Set up Nix
+        uses: cachix/install-nix-action@v17
 
-      - name: Install Dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y xorg x11-utils x11-xserver-utils xfonts-base libxrender1 libxext6 libxtst6 libxi6 xfonts-100dpi xfonts-75dpi mesa-utils xvfb xdotool
-
-      - name: Start Xvfb
-        run: |
-          Xvfb :99 -screen 0 1024x768x16 &
-          export DISPLAY=:99
-          sleep 3
-          DISPLAY=:99 xvinfo
-
-      - name: Download and Extract Reaper
-        run: |
-          latest_version=${{ needs.check-reaper-version.outputs.latest_version }}
-          file_tag=${latest_version%%.*} # retain only the major version
-          reap_tag=${latest_version//./} # remove the '.'
-          reap_tar="reaper${reap_tag}_linux_x86_64.tar.xz"
-          curl -sL -o "$reap_tar" "https://www.reaper.fm/files/${file_tag}.x/${reap_tar}"
-          tar -xf $reap_tar
-
-      - name: Clone reaper-sdk repository fork
+      - name: Clone reaper-sdk fork
         run: |
           mkdir temp
           cd temp
@@ -103,18 +83,22 @@ jobs:
 
       - name: Generate header file
         run: |
-          DISPLAY=:99 xvinfo
-          # Run the header generation script, overwriting the old header file.
-          # The runner path is:
-          # /home/runner/work/reascript-rs/reascript-rs/reaper_linux_x86_64/REAPER/reaper
-          xvfb-run -a ./generate-reaper-plugin-functions/run.sh /home/runner/work/reascript-rs/reascript-rs/reaper_linux_x86_64/REAPER/reaper /home/runner/work/reascript-rs/reascript-rs/generate-reaper-plugin-functions /home/runner/work/reascript-rs/reascript-rs/temp/reaper-sdk/sdk
+          latest_version=${{ needs.check-reaper-version.outputs.latest_version }}
+          nix build .#reaper-plugin-functions
+          cp result/include/reaper_plugin_functions.h temp/reaper-sdk/sdk/reaper_plugin_functions.h
+          generated_version=$(cat temp/reaper-sdk/sdk/reaper_plugin_function.h | grep -oP '// Generated by REAPER v\K[0-9]+(\.[0-9]+)+' || echo "Current Version Not Found" & exit 1)
+          if [[ "$generated_version" -ne "$latest_version" ]]; then
+              echo "Expected version '$latest_version' but the generated version is '$generated_version'"
+              exit 1
+          fi
 
       - name: Commit and push changes
         run: |
           latest_version=${{ needs.check-reaper-version.outputs.latest_version }}
           git config --global user.email "cloudscythelabs@gmail.com"
           git config --global user.name "Cloud Scythe Labs"
-          cd temp
+          cd temp/reaper-sdk/sdk
+          git status
           git checkout -b update-header-${latest_version}
           git add reaper_plugin_functions.h
           git commit -m "Update Reaper C++ API functions header to version ${latest_version}"
